# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6dd24557bb4b944f0a7303de03fbde6a0dde15662b160390648af3a2f1e3fe7078b739bca82bcfe74b199a41cbd392c631090dd223a884746f246d7ec4204d05

test:
  secret_key_base: 928e8ea7793effe4289a1655a809e79b52ab5bda9e62b09b09e111199e8c7efbad72c54a09135b362b2718c2489c17e4ffdce4799c787277200e39cccd981708

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
